# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'PickleHub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PickleHub
  pod 'Kingfisher', '~> 7.0'

  # Firebase for Push Notifications
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  # Google Maps
  pod 'GoogleMaps', '~> 8.0'
  pod 'GooglePlaces', '~> 8.0'

end
